name: rick_and_morty_database
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #widgets
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  flutter_dropdown: ^1.0.1+hotfix.1

  #icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0

  #HTTP
  dio: ^5.2.1+1

  #Injection and state manager
  get_it: ^7.6.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  #router
  go_router: ^9.0.3

  #local storage
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4

  #utils
  logger: ^1.4.0
  path: ^1.8.3
  connectivity_plus: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
